# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MY6268huaqCvAvahqtL8GzXBC7h-eoyp
"""

import random
import numpy

from prettytable import PrettyTable

# Генерація випадкових точок
def monte_carlo_simulation(num_experiments):
    """Виконує серію експериментів методом Монте-Карло."""

    countSum = {}
    # Генерація суми що випадає в на кубиках
    sum = [(random.randint(1, 6) + random.randint(1, 6)) for _ in range(num_experiments)]

    for x in numpy.sort(sum):
        if x not in countSum:
            countSum[x] = 1
        else:
            countSum[x] = countSum[x]+1

    return countSum
# Кількість підкиданнь кубика
n = 1000000
listSum = monte_carlo_simulation(n)

myTable = PrettyTable(["Сума", "Імовірність %"])

# Add rows
for x in range(2, 13):
    myTable.add_row([x, listSum[x]*100/n])


print(myTable)