# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTpGu5lsY5NgGazS51aEBh8h4mMcwD3K
"""

!pip install pulp

import pulp

# Ініціалізація моделі
model = pulp.LpProblem("Maximize_Product", pulp.LpMaximize)

# Визначення змінних
A = pulp.LpVariable('A', lowBound=0, cat='Integer')  # Кількість продукту А
B = pulp.LpVariable('B', lowBound=0, cat='Integer')  # Кількість продукту Б

# Функція цілі (Максимізація виробництва)
model += A + B, "Profit"

# Додавання обмежень
model += 2 * A + B <= 100  # Обмеження для води
model += A  <= 50  # Обмеження для цукру
model += A <= 30 # Обмеження для лимонного соку
model += 2 * B <= 40 # Обмеження для фруктового соку

# Розв'язання моделі
model.solve()

# Вивід результатів
print("Виробляти лимонаду:", A.varValue)
print("Виробляти фруктового соку:", B.varValue)